 name: my First Workflow
 on: workflow_dispatch
 jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: hellojob
        run: echo " Welcome To a Job"

  Printer:
    runs-on: ubuntu-latest
    steps:
      - name: sayhi
        run: echo "Say! Hii"
    # steps:
    #   - name: Intentional_Error
    #     run: echo "This will fail"
